# fly.toml app configuration file generated for aitechj-frontend-v2 on 2025-06-29T03:16:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aitechj-frontend-v2'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '3000'
  NODE_ENV = 'production'
  NEXT_PUBLIC_API_URL = 'https://aitechj-backend-v2.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
