# fly.toml app configuration file generated for aitechj-backend on 2025-06-28T09:38:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aitechj-backend'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'
  SPRING_PROFILES_ACTIVE = 'production'

[[mounts]]
  source = 'aitechj_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '20s'
    grace_period = '30s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
