# fly.toml app configuration file template for fresh setup
# Replace aitechj-backend-v2 and aitechj_backend_v2_data with actual values

app = 'aitechj-backend-v2'
primary_region = 'syd'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '8080'
  SPRING_PROFILES_ACTIVE = 'fly'
  JDBC_URL = ''
  DB_USERNAME = ''
  DB_PASSWORD = ''
  JWT_SECRET = ''


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '20s'
    grace_period = '30s'
    method = 'GET'
    path = '/actuator/health'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
# Trigger deployment after fly.toml environment variable fix - Sat Jul  5 09:55:26 UTC 2025
