spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/learning_portal}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 60000

logging:
  level:
    com.aiportal.learning: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN
