# Fly.io specific configuration for PostgreSQL deployment
server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://direct.nlkxjo585d4oy93v.flympg.net:5432/pgdb-nlkxjo585d4oy93v?sslmode=require}
    username: ${DB_USERNAME:pgdb-nlkxjo585d4oy93v}
    password: ${DB_PASSWORD:ypE2fFgZdOpdL4OM9Zm3JsCx}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 60000

logging:
  level:
    com.aiportal.learning: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: WARN
# Force deployment with server binding fix - Fri Jul  4 07:57:05 UTC 2025
# Trigger CI to verify e2e-tests pass with corrected backend - Fri Jul  4 15:36:19 UTC 2025
