name: Lighthouse Performance Testing

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build shared types package
        run: cd shared-types && npm run build
      
      - name: Reinstall dependencies to link shared types
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app
        run: pnpm run build

      - name: Start Next.js on port 3000
        run: |
          echo "Starting Next.js..."
          pnpm start &
          npx wait-on http://localhost:3000 --timeout 60000 --verbose
        env:
          NEXT_PUBLIC_API_URL: https://aitechj-backend-v2.fly.dev

      - name: Run Lighthouse CI
        run: |
          npx @lhci/cli collect --url=http://localhost:3000
          npx @lhci/cli assert \
            --assertions.categories:performance=error,minScore=0.6 \
            --assertions.categories:accessibility=error,minScore=0.7 \
            --assertions.categories:best-practices=error,minScore=0.7 \
            --assertions.categories:seo=error,minScore=0.8
