name: Lighthouse Performance Testing

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build shared types package
        run: cd shared-types && npm run build
      
      - name: Reinstall dependencies to link shared types
        run: pnpm install --frozen-lockfile
      
      - name: Build Next.js app
        run: pnpm build
      
      - name: Start Next.js app
        run: pnpm start &
        env:
          NEXT_PUBLIC_API_URL: https://aitechj-backend-v2.fly.dev
      
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
      
      - name: Run Lighthouse CI
        run: |
          lhci autorun \
            --collect.url="http://localhost:3000" \
            --collect.url="http://localhost:3000/dashboard" \
            --collect.url="http://localhost:3000/admin" \
            --collect.url="http://localhost:3000/profile" \
            --collect.numberOfRuns=3 \
            --collect.staticDistDir=".next" \
            --collect.settings.chromeFlags="--no-sandbox --disable-dev-shm-usage --disable-gpu --headless --disable-web-security --disable-features=VizDisplayCompositor" \
            --assert.assertions.categories:performance=error,minScore:0.8 \
            --assert.assertions.categories:accessibility=error,minScore:0.9 \
            --assert.assertions.first-contentful-paint=error,maxNumericValue:2000 \
            --assert.assertions.largest-contentful-paint=error,maxNumericValue:3000 \
            --upload.target=temporary-public-storage
        env:
          LHCI_BUILD_CONTEXT__CURRENT_HASH: ${{ github.sha }}
          LHCI_BUILD_CONTEXT__COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.ref_name }}
          LHCI_BUILD_CONTEXT__COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      
      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-reports
          path: .lighthouseci/
